maxRestCallDurationInMinutes:
  configValueType: "LONG"
  configValueCount: "SINGLE"
  valueAsJson: "ddddddseldddamlar"
  encrypted: false
voiceAdminBaseUri:
  configValueType: "STRING"
  configValueCount: "SINGLE"
  valueAsJson: "/"
  encrypted: false
