alcatelAgentActivityMonitorReportIntervalInMinutes: 31
alcatelBipToneGenerationPresenceTimer: 50
alcatelBipToneGenerationSilenceTimer: 0
alcatelBipToneGenerationTonality: 565
alcatelCallConversationLoggerTarget: "TargetTypeDB"
alcatelCallEventLoggerTarget: "TargetTypeDB"
alcatelConfigServerLookupPeriodInMinutes: 1
alcatelCtiExecutionMode: "P"
alcatelMonitoredExtensionRange: "self.In(144,142,144,1001,1002,1004,2000)"
alcatelTelephonyServerPrimaryHost: "192.168.2.180"
alcatelTelephonyServerStandbyHost: "192.168.2.180"
archiveLocation: "D:\\SistasVoiceData\\Archived"
archivePassword: "asdf<asdf"
archiveType: "localdd"
cacheClearPeriodInMinutes: 1
clusteredInstanceCount: 1
compressorName: "speexenc.exe"
compressorPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceServer\\\
  bin\\x64\\Release\\distribution\\compressor\\2016_11_11_11_11_11"
configurationPublishingPeriodInSeconds: 60
connectionString: "Data Source=localhost; Initial Catalog=sisvoice;User Id=sa; Password=sistas_1"
converterName: "dec729cp_x86.exe"
converterPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceServer\\\
  bin\\x64\\Release\\distribution\\converter\\2016_11_11_11_11_11"
databaseType: "MSSQL"
encryptionName: "openssl.exe"
encryptionPath: "D:\\github\\SistasYazilimGrubu\\SistasVoiceSolution\\SistasVoiceServer\\\
  bin\\x64\\Release\\distribution\\encryptor\\2016_11_11_11_11_11"
filePurgeBaseDirectory: "C:\\Users\\KC-PC\\AppData\\Local\\Temp\\"
filePurgeFileNameRegex: "^[A-Fa-f0-9]{32}$"
filePurgePeriodInMinutes: 1
genesysCallConversationLoggerTarget: "TargetTypeDB"
genesysCallEventDataMappingDefinition: "|1=ADagentid|2=ADextension|3=ADqueue|4=ADpassword|5=ADagentip|"
genesysCallEventLoggerTarget: "TargetTypeDB"
genesysConfigServerLookupPeriodInMinutes: 1
genesysConversationDataMappingDefinition: "|1=ADagentid|2=ADextension|3=ADqueue|4=ADpassword|5=ADagentip|"
genesysCtiExecutionMode: "P"
genesysFailFullDirectoryName: "D:\\dump\\GenesysFail"
genesysMonitoredExtensionRange: "self.In(144,142,144, 1001,1002,1004,1031)"
genesysTelephonyServerPrimaryHost: "192.168.2.180"
genesysTelephonyServerPrimaryPort: 3100
genesysTelephonyServerRtpPassword: "sistas_1"
genesysTelephonyServerStandbyHost: "192.168.2.180"
genesysTelephonyServerStandbyPort: 3103
instanceId: "Server001"
isActiveRecordingEnabled: true
isAlcatelBipToneGenerationEnabled: true
isAlcatelConfigServerEnabled: false
isAlcatelCtiHighAvailabilityEnabled: false
isAlcatelTelephonyServerEnabled: true
isAlcatelTsapiEnabledandStartRecordingDisabled: false
isAllInOneConfiguration: false
isCTICheckEnabled: true
isCacheClearEnabled: true
isCallEventLogEnabled: false
isCompressionEnabled: true
isEnvironmentMetricsEnabled: true
isFilePurgeEnabled: false
isGenesysActiveRecordingEnabled: true
isGenesysConfigServerEnabled: false
isGenesysCtiHighAvailabilityEnabled: false
isGenesysForceCTIReregisterOnLookupPeriod: false
isGenesysLoggingEnabled: true
isGenesysTelephonyServerEnabled: false
isImpersonationCachingEnabled: false
isMigrated: true
isResourceListeningEnabled: true
isRestartProcessManagement: false
isScreenRecordingEnabled: true
isSistasConfigurationServerConfigUploadOnStartEnabled: true
isSistasConfigurationServerEnabled: true
isSkipCacheEnabled: false
managedCapturerClusterId: "Cluster001"
maxCacheExecutionActorCount: 3
maxCacheExecutionThreadCountPerActor: 1
maxCallCountInConversation: 9
mediaAttachmentTarget: "alcatel"
metricsPublishingPeriodInSeconds: 61
minRemoveExpiredCallPartyContextInHours: 6
oAuth2ClientSecret: "d894a029-3468-49e7-812e-99b60d24e0d6"
prometheusHostname: "127.0.0.1"
prometheusPort: 28017
resourceListenBaseUri: "/SisBackupServer/BackupService/"
resourceListenHost: "127.0.0.1"
resourceListenPort: 28002
restAccessToken: "asdfghjkl"
serviceRegisterRequestArgumentType: 11
sistasConfigurationServerDownloadPeriodInMinutes: 30
statisticPeriod: 900003
voiceAdminHost: "127.0.0.1"
voiceAdminPort: 28015
webServerHost: "127.0.0.1"
webServerPort: 28005
